const {test}=require('node:test');
const assert=require('node:assert/strict');
const Detector=require('../extension/detector.js');
const base={route:'/c/test',user:'u1',enabled:true,busy:false,ready:true,message:'old',blocked:false,error:false};
function snap(change={}){return {...base,...change};}
function finish(d,id='new',t=100){assert.equal(d.step(snap({message:id}),t),null);return d.step(snap({message:id}),t+2000);}
test('opening old chat does not notify',()=>{const d=new Detector();assert.equal(d.step(base,0),null);assert.equal(d.step(base,5000),null);});
test('normal completion waits for final controls and settles, exactly once',()=>{const d=new Detector();d.step(snap({busy:true}),0);assert.equal(d.step(snap({message:'new',ready:false}),20),null);assert.equal(finish(d),'new');assert.equal(d.step(snap({message:'new'}),9999),null);});
test('attaching during active answer can notify',()=>{const d=new Detector();d.step(snap({busy:true,ready:false,message:'new'}),0);assert.equal(finish(d),'new');});
test('old copy controls while starting a new response do not notify',()=>{const d=new Detector();d.step(snap({busy:true}),0);d.step(base,100);assert.equal(d.step(base,6000),null);});
test('temporary stop-button disappearance cannot finish without a new final answer',()=>{const d=new Detector();d.step(snap({busy:true,ready:false,message:''}),0);d.step(snap({ready:false,message:''}),100);assert.equal(d.step(snap({ready:false,message:''}),4000),null);d.step(snap({busy:true,ready:false,message:'new'}),4100);assert.equal(finish(d,'new',5000),'new');});
test('generation restarts during settle period',()=>{const d=new Detector();d.step(snap({busy:true}),0);d.step(snap({message:'new'}),100);d.step(snap({busy:true,message:'new'}),1000);assert.equal(d.step(snap({message:'new'}),2500),null);assert.equal(d.step(snap({message:'new'}),4500),'new');});
test('a route-scoped assistant turn does not re-complete when Work changes user and message ids',()=>{const d=new Detector();const first='/c/test\u001fconversation-turn-1',second='/c/test\u001fconversation-turn-2';d.step(snap({busy:true,ready:false,message:'',turn:''}),0);assert.equal(d.step(snap({message:'m1',turn:first}),100),null);assert.equal(d.step(snap({message:'m1',turn:first}),2100),first);assert.equal(d.step(snap({busy:true,ready:false,message:'m2',turn:first}),3000),null);assert.equal(d.step(snap({user:'u2',message:'m2',turn:first}),5000),null);d.step(snap({user:'u3',busy:true,ready:false,message:'',turn:''}),6000);assert.equal(d.step(snap({user:'u3',message:'m3',turn:second}),6100),null);assert.equal(d.step(snap({user:'u3',message:'m3',turn:second}),8100),second);});
test('manual stop suppresses partial reply but subsequent turn works',()=>{const d=new Detector();d.step(snap({busy:true}),0);d.cancel();assert.equal(d.step(snap({message:'partial'}),100),null);assert.equal(d.step(snap({message:'partial'}),5000),null);d.step(snap({busy:true,user:'u2'}),6000);d.step(snap({user:'u2',message:'second'}),6100);assert.equal(d.step(snap({user:'u2',message:'second'}),8200),'second');});
test('navigation to another chat does not notify',()=>{const d=new Detector();d.step(snap({busy:true}),0);const other=snap({route:'/c/other',message:'other'});d.step(other,100);assert.equal(d.step(other,4000),null);});
test('new chat URL promotion retains active generation',()=>{const d=new Detector();d.step(snap({route:'/',busy:true,ready:false,message:''}),0);assert.equal(finish(d),'new');});
test('disable then enable does not notify a historical answer',()=>{const d=new Detector();d.step(snap({busy:true}),0);d.step(snap({enabled:false}),100);assert.equal(finish(d),null);});
test('approval dialog and error suppress completion',()=>{for(const flag of ['blocked','error']){const d=new Detector();d.step(snap({busy:true}),0);d.step(snap({[flag]:true,message:'new'}),100);assert.equal(finish(d),null);}});
test('different tabs each notify independently',()=>{const a=new Detector(),b=new Detector();a.step(snap({busy:true}),0);b.step(snap({busy:true}),0);assert.equal(finish(a,'a'),'a');assert.equal(finish(b,'b'),'b');});

test('hidden-toolbar fallback requires four seconds of stable final metadata',()=>{const d=new Detector();d.step(snap({busy:true,ready:false,message:''}),0);assert.equal(d.step(snap({ready:true,provisional:true,message:'new'}),100),null);assert.equal(d.step(snap({ready:true,provisional:true,message:'new'}),2200),null);assert.equal(d.step(snap({ready:true,provisional:true,message:'new'}),4100),'new');});
test('busy resuming cancels a provisional hidden completion',()=>{const d=new Detector();d.step(snap({busy:true,ready:false,message:''}),0);d.step(snap({ready:true,provisional:true,message:'new'}),100);d.step(snap({busy:true,ready:false,message:'new'}),3000);assert.equal(d.step(snap({ready:true,provisional:true,message:'new'}),3100),null);assert.equal(d.step(snap({ready:true,provisional:true,message:'new'}),6000),null);assert.equal(d.step(snap({ready:true,provisional:true,message:'new'}),7100),'new');});

test('second user turn starts generating before stop control appears',()=>{const d=new Detector();d.step(snap({busy:true}),0);d.step(snap({message:'first'}),100);assert.equal(d.step(snap({message:'first'}),2100),'first');assert.equal(d.active,false);d.step(snap({user:'u2',ready:false,message:'',busy:false}),3000);assert.equal(d.active,true);});
test('same-route historical branch change with a ready answer does not start generating',()=>{const d=new Detector();d.step(base,0);d.step(snap({user:'u2',ready:true,message:'historical'}),100);assert.equal(d.active,false);assert.equal(d.step(snap({user:'u2',ready:true,message:'historical'}),5000),null);});

const opaque=(n,change={})=>snap({user:'',message:'',turn:`/c/test\u001fconversation-turn-${n}`,ready:false,...change});
test('initial role-less turn is only a baseline, even before its final action appears',()=>{const d=new Detector();assert.equal(d.step(opaque(40),0),null);assert.equal(d.active,false);assert.equal(d.step(opaque(40,{ready:true}),3000),null);assert.equal(d.active,false);});
test('new role-less turn starts generating and completes once; second job also works',()=>{const d=new Detector();d.step(opaque(40),0);for(const [n,t] of [[41,100],[42,5000]]){assert.equal(d.step(opaque(n),t),null);assert.equal(d.active,true);assert.equal(d.step(opaque(n,{ready:true}),t+100),null);assert.equal(d.step(opaque(n,{ready:true}),t+2100),opaque(n).turn);assert.equal(d.active,false);assert.equal(d.step(opaque(n,{ready:true}),t+3000),null);}});
test('ready role-less historical branch updates baseline without generating',()=>{const d=new Detector();d.step(opaque(40,{ready:true}),0);assert.equal(d.step(opaque(41,{ready:true}),100),null);assert.equal(d.active,false);assert.equal(d.step(opaque(41,{ready:false}),200),null);assert.equal(d.active,false);assert.equal(d.step(opaque(41,{ready:true}),5000),null);});
test('role-less navigation does not start a generation',()=>{const d=new Detector();d.step(opaque(40),0);const other=opaque(41,{route:'/c/other',turn:'/c/other\u001fconversation-turn-41'});d.step(other,100);assert.equal(d.active,false);assert.equal(d.step({...other,ready:true},3000),null);});
test('role-less manual stop suppresses partial completion but allows the next turn',()=>{const d=new Detector();d.step(opaque(40),0);d.step(opaque(41),100);assert.equal(d.active,true);d.cancel();d.step(opaque(41),200);assert.equal(d.active,false);assert.equal(d.step(opaque(41,{ready:true}),3000),null);d.step(opaque(42),4000);assert.equal(d.active,true);d.step(opaque(42,{ready:true}),4100);assert.equal(d.step(opaque(42,{ready:true}),6100),opaque(42).turn);});
test('role-less errors and approval dialogs do not resume the same partial turn',()=>{for(const flag of ['error','blocked']){const d=new Detector();d.step(opaque(40),0);d.step(opaque(41),100);d.step(opaque(41,{[flag]:true}),200);d.step(opaque(41),300);assert.equal(d.active,false);assert.equal(d.step(opaque(41,{ready:true}),3000),null);}});
