const fixture=document.getElementById('fixture'),result=document.getElementById('results');
document.getElementById('run').onclick=()=>{
 const outcomes=[];function test(name,fn){try{fn();outcomes.push('PASS '+name);}catch(e){outcomes.push('FAIL '+name+': '+e.message);}}
 function eq(a,b){if(a!==b)throw Error(String(a)+' !== '+String(b));}
 const user='<section data-turn="user"><div data-message-author-role="user" data-message-id="user">fixture question</div><button data-testid="copy-turn-action-button">Copy user</button></section>';
 const answer='<section data-turn="assistant"><div data-message-author-role="assistant" data-message-id="answer">fixture answer</div><button data-testid="copy-turn-action-button">Copy answer</button></section>';
 const stop='<button data-testid="stop-button" aria-label="回答を停止">Stop</button>';
 function read(){return ChappyDOM.read(document,'/c/fixture',true);}
 test('現行ChatGPTのsection構造で完了を検出',()=>{fixture.innerHTML=user+answer;eq(read().ready,true);eq(read().message,'answer');eq(read().user,'user');eq(read().busy,false);});
 test('role要素が無い現行ターンでもroute-scoped turn-idと最終操作で完了を検出',()=>{fixture.innerHTML=user+'<section data-turn="assistant" data-turn-id="turn-answer"><button data-testid="copy-turn-action-button">Copy answer</button></section>';eq(read().ready,true);eq(read().message,'turn-answer');eq(read().turn,'/c/fixture\u001fturn-answer');eq(read().busy,false);});
 test('assistant turn testid is route-scoped when data-turn-id is absent',()=>{fixture.innerHTML=user+'<section data-turn="assistant" data-testid="conversation-turn-42"><div data-message-author-role="assistant" data-message-id="answer"></div><button data-testid="copy-turn-action-button">Copy answer</button></section>';eq(read().turn,'/c/fixture\u001fconversation-turn-42');});
 test('assistant conversation turn testid wins over mutable data-turn-id',()=>{fixture.innerHTML=user+'<section data-turn="assistant" data-testid="conversation-turn-42" data-turn-id="mutable-turn"><div data-message-author-role="assistant" data-message-id="answer"></div><button data-testid="copy-turn-action-button">Copy answer</button></section>';eq(read().turn,'/c/fixture\u001fconversation-turn-42');});
 test('生成中のstop-buttonを検出',()=>{fixture.innerHTML=user+answer+stop;eq(read().busy,true);});
 test('exact Stop label starts generation',()=>{fixture.innerHTML=user+'<form data-chatgpt-composer><button type="button" aria-label="Stop"></button></form>';eq(read().busy,true);eq(read().visibleStop,true);});
 test('hidden or transparent exact Stop label is ignored',()=>{for(const markup of ['<button aria-label="Stop" hidden></button>','<div style="display:none"><button aria-label="Stop"></button></div>','<button aria-label="Stop" style="visibility:hidden"></button>','<button aria-label="Stop" style="opacity:0"></button>']){fixture.innerHTML=user+markup;eq(read().busy,false);eq(read().visibleStop,false);}});
 test('過去の回答があっても最新userへの応答待ちは未完了',()=>{fixture.innerHTML=answer+user;eq(read().ready,false);eq(read().message,'');});
 test('Workの途中sectionに本文も最終操作もなければ未完了',()=>{fixture.innerHTML=user+'<section data-turn="assistant"><button>ツールを使用しました</button></section>'+stop;eq(read().ready,false);eq(read().busy,true);});
 test('コピー操作のない途中出力は未完了',()=>{fixture.innerHTML=user+'<section data-turn="assistant"><div data-message-author-role="assistant" data-message-id="partial">working</div></section>';eq(read().ready,false);});
 test('非表示のstop-buttonを無視',()=>{fixture.innerHTML=user+answer+'<div style="display:none">'+stop+'</div>';eq(read().busy,false);});
 test('透明なstop-buttonを無視',()=>{fixture.innerHTML=user+answer+stop;fixture.querySelector('[data-testid="stop-button"]').style.opacity='0';eq(read().busy,false);});
 test('ホバーまで透明なコピー操作を許容',()=>{fixture.innerHTML=user+answer;fixture.querySelector('[data-turn="assistant"] button').style.opacity='0';eq(read().ready,true);});
 test('非表示の最終操作では完了しない',()=>{fixture.innerHTML=user+answer;fixture.querySelector('[data-turn="assistant"] button').style.display='none';eq(read().ready,false);});
 test('承認ダイアログ表示中は待機',()=>{fixture.innerHTML=user+answer+'<div role="dialog">fixture approval</div>';eq(read().blocked,true);});
 test('エラーUIを検出',()=>{fixture.innerHTML=user+answer+'<div role="alert">ネットワークエラーが発生しました</div>';eq(read().error,true);});
 test('回答にerrorという単語があってもエラーにしない',()=>{fixture.innerHTML=user+answer.replace('fixture answer','Something went wrong is an error message');eq(read().error,false);});
 test('DOMから検出器までの通常応答フロー',()=>{const d=new ChappyCompletionDetector(2000);fixture.innerHTML=user+stop;eq(d.step(read(),0),null);fixture.innerHTML=user+answer;eq(d.step(read(),100),null);eq(d.step(read(),2100),'answer');eq(d.step(read(),5000),null);});
 test('二つ目の新規応答も一度だけ通知',()=>{const d=new ChappyCompletionDetector();fixture.innerHTML=user+stop;d.step(read(),0);fixture.innerHTML=user+answer;d.step(read(),10);eq(d.step(read(),2010),'answer');fixture.innerHTML=user+answer+user.replaceAll('"user"','"user2"').replace('data-turn="user2"','data-turn="user"').replace('data-message-author-role="user2"','data-message-author-role="user"')+stop;d.step(read(),3000);fixture.innerHTML=user+answer+user.replace('data-message-id="user"','data-message-id="user2"')+answer.replace('data-message-id="answer"','data-message-id="answer2"');d.step(read(),3100);eq(d.step(read(),5100),'answer2');});
 test('非表示タブでは最終操作未描画でもassistant message-id確定後を暫定完了にする',()=>{Object.defineProperty(document,'visibilityState',{value:'hidden',configurable:true});fixture.innerHTML=user+'<section data-turn="assistant" data-turn-id="turn-bg"><div data-message-author-role="assistant" data-message-id="answer-bg"></div></section>';const x=read();eq(x.ready,true);eq(x.provisional,true);eq(x.busy,false);Object.defineProperty(document,'visibilityState',{value:'visible',configurable:true});});
 test('前面タブでは最終操作のないassistant message-idだけで完了にしない',()=>{Object.defineProperty(document,'visibilityState',{value:'visible',configurable:true});fixture.innerHTML=user+'<section data-turn="assistant" data-turn-id="turn-front"><div data-message-author-role="assistant" data-message-id="answer-front"></div></section>';const x=read();eq(x.ready,false);eq(x.provisional,false);});
 test('非表示でもstop表示中は暫定完了にしない',()=>{Object.defineProperty(document,'visibilityState',{value:'hidden',configurable:true});fixture.innerHTML=user+'<section data-turn="assistant" data-turn-id="turn-busy"><div data-message-author-role="assistant" data-message-id="answer-busy"></div></section>'+stop;const x=read();eq(x.busy,true);eq(x.ready,false);eq(x.provisional,false);Object.defineProperty(document,'visibilityState',{value:'visible',configurable:true});});
 const opaque=(n,final=false)=>`<section data-testid="conversation-turn-${n}"><div>fixture prose must not be read</div>${final?'<button data-testid="copy-turn-action-button">Copy</button>':''}</section>`;
 test('role-less wrapper is opaque metadata only; initial load never completes',()=>{fixture.innerHTML=opaque(40);const body=fixture.querySelector('section div');Object.defineProperty(body,'textContent',{get(){throw Error('message prose read');}});const x=read(),d=new ChappyCompletionDetector();eq(x.turn,'/c/fixture\u001fconversation-turn-40');eq(x.user,'');eq(x.message,'');eq(x.ready,false);eq(d.step(x,0),null);eq(d.active,false);});
 test('role-less added turn and final action complete once, including second job',()=>{const d=new ChappyCompletionDetector();fixture.innerHTML=opaque(40,true);d.step(read(),0);for(const [n,t] of [[41,100],[42,5000]]){fixture.innerHTML+=opaque(n);eq(read().busy,false);eq(read().ready,false);eq(d.step(read(),t),null);eq(d.active,true);fixture.querySelector(`[data-testid="conversation-turn-${n}"]`).innerHTML='<button data-testid="copy-turn-action-button">Copy</button>';eq(read().ready,true);eq(d.step(read(),t+100),null);eq(d.step(read(),t+2100),`/c/fixture\u001fconversation-turn-${n}`);eq(d.step(read(),t+3000),null);}});
 test('role-less old chat and completed historical branch never generate',()=>{const d=new ChappyCompletionDetector();fixture.innerHTML=opaque(40,true);eq(d.step(read(),0),null);eq(d.active,false);fixture.innerHTML=opaque(90,true);eq(d.step(read(),100),null);eq(d.active,false);eq(d.step(read(),3000),null);});
 test('latest role-less wrapper supersedes older typed turns; hidden copy is not final',()=>{fixture.innerHTML=user+answer+opaque(41,true);fixture.querySelector('[data-testid="conversation-turn-41"] button').hidden=true;eq(read().turn,'/c/fixture\u001fconversation-turn-41');eq(read().ready,false);});
 test('explicit user role inside conversation wrapper never counts as final',()=>{fixture.innerHTML='<section data-testid="conversation-turn-41"><div data-message-author-role="user" data-message-id="user41"></div><button data-testid="copy-turn-action-button">Copy</button></section>';eq(read().ready,false);});
 test('conversation wrapper itself can carry existing assistant metadata',()=>{fixture.innerHTML='<section data-testid="conversation-turn-41" data-message-author-role="assistant" data-message-id="self-answer"><button data-testid="copy-turn-action-button">Copy</button></section>';eq(read().message,'self-answer');eq(read().ready,true);eq(read().turn,'/c/fixture\u001fconversation-turn-41');});
 fixture.innerHTML='';result.textContent=outcomes.join('\n')+'\nTOTAL '+outcomes.length+' / FAIL '+outcomes.filter(x=>x.startsWith('FAIL')).length;
};
