const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const {webcrypto}=require('node:crypto');
const {parseHTML}=require(require.resolve('linkedom',{paths:[process.env.CHAPPY_DOM_DEPENDENCIES||__dirname]}));
(async()=>{
 const {document,window}=parseHTML('<!doctype html><html><body><main></main></body></html>');
 window.HTMLElement.prototype.getClientRects=function(){return [{}];};
 window.getComputedStyle=e=>({display:e.style.display||'block',visibility:e.style.visibility||'visible',opacity:e.style.opacity||'1'});
 let tick,now=0;const sent=[],listeners=[];
 const chrome={runtime:{sendMessage:async msg=>{sent.push(msg);return msg.target==='settings'?{enabled:false}:{ok:true};},onMessage:{addListener:f=>listeners.push(f)}}};
 const context=vm.createContext({document,window,location:{pathname:'/c/fixture'},Element:window.Element,MutationObserver:window.MutationObserver,chrome,crypto:webcrypto,TextEncoder,Date:{now:()=>now},queueMicrotask,setTimeout:()=>1,clearTimeout:()=>{},setInterval:f=>{tick=f;return 1;},clearInterval:()=>{},console});
 for(const f of ['detector.js','dom-reader.js','content.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'../extension',f),'utf8'),context);
 await new Promise(setImmediate);
 const main=document.querySelector('main');
 const busy='<section data-turn="user"><div data-message-author-role="user" data-message-id="user1">private prompt</div></section><button data-testid="stop-button">Stop</button>';
 const final=busy.replace('<button data-testid="stop-button">Stop</button>','<section data-turn="assistant"><div data-message-author-role="assistant" data-message-id="message1">private answer</div><button data-testid="copy-turn-action-button">Copy</button></section>');
 main.innerHTML=busy;await tick();main.innerHTML=final;now=100;await tick();now=3000;await tick();assert.equal(sent.filter(m=>m.type==='COMPLETE').length,0);
 console.log('PASS 初期オフ状態では通知しない');
 listeners.forEach(f=>f({type:'SET_ENABLED',enabled:true}));main.innerHTML=busy;now=4000;await tick();main.innerHTML=final;now=4100;await tick();now=6200;await tick();now=7000;await tick();
 const completions=sent.filter(m=>m.type==='COMPLETE');assert.equal(completions.length,1);assert.match(completions[0].key,/^[a-f0-9]{64}$/);assert.equal(JSON.stringify(sent).includes('private'),false);assert.equal(JSON.stringify(sent).includes('message1'),false);
 assert.deepEqual(sent.filter(m=>m.type==='STATUS').slice(-2).map(m=>m.state),['generating','complete']);
 console.log('PASS 読込済みタブの有効化・黄色→青色・1回のハッシュ通知まで通過');
 const pendingSecond=final+'<section data-turn="user"><div data-message-author-role="user" data-message-id="user2">second private prompt</div></section>';
 main.innerHTML=pendingSecond;now=7500;await tick();assert.equal(sent.filter(m=>m.type==='STATUS').at(-1).state,'generating');
 console.log('PASS 青色完了後の2回目はstop表示前でも新user turnで作業中へ戻る');
 main.innerHTML=busy.replace('user1','user2');now=8000;await tick();main.querySelector('button').dispatchEvent(new window.Event('click',{bubbles:true}));main.innerHTML=final.replace('user1','user2').replace('message1','message2');now=8100;await tick();now=11000;await tick();assert.equal(sent.filter(m=>m.type==='COMPLETE').length,1);
 assert.equal(sent.filter(m=>m.type==='STATUS').at(-1).state,'watching');
 console.log('PASS 手動停止クリックで音声・青色表示を抑止');
 main.innerHTML=busy.replace('user1','user3');now=12000;await tick();main.innerHTML=final.replace('user1','user3').replace('message1','message3');now=12100;await tick();now=15000;await tick();assert.equal(sent.filter(m=>m.type==='STATUS').at(-1).state,'complete');
 context.location.pathname='/c/other';now=15100;await tick();assert.equal(sent.filter(m=>m.type==='STATUS').at(-1).state,'watching');
 console.log('PASS 別チャットへの画面移動で完了色を解除');
 context.location.pathname='/c/roleless';
 const opaque=(n,ready=false)=>`<section data-testid="conversation-turn-${n}"><div>private fixture prose</div>${ready?'<button data-testid="copy-turn-action-button">Copy</button>':''}</section>`;
 const completedBefore=sent.filter(m=>m.type==='COMPLETE').length;
 main.innerHTML=opaque(40,true);now=16000;await tick();assert.equal(sent.filter(m=>m.type==='STATUS').at(-1).state,'watching');
 for(const [n,t] of [[41,17000],[42,21000]]){
  main.innerHTML+=opaque(n);now=t;await tick();assert.equal(sent.filter(m=>m.type==='STATUS').at(-1).state,'generating');
  main.querySelector(`[data-testid="conversation-turn-${n}"]`).innerHTML='<button data-testid="copy-turn-action-button">Copy</button>';now=t+100;await tick();now=t+2100;await tick();now=t+2500;await tick();
  assert.equal(sent.filter(m=>m.type==='STATUS').at(-1).state,'complete');assert.equal(sent.filter(m=>m.type==='COMPLETE').length,completedBefore+n-40);
 }
 assert.equal(JSON.stringify(sent).includes('private'),false);assert.equal(JSON.stringify(sent).includes('conversation-turn-'),false);
 console.log('PASS role-less turn fallback sends generating then exactly one hashed completion per job');
 console.log('TOTAL 6 / FAIL 0');
})().catch(e=>{console.error(e);process.exitCode=1;});
